services:
  qodo-pr-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-dial-poc/qodo-merge-instrumented
    container_name: qodo-pr-agent
    command:
      - --pr_url
      - $GITHUB_PR_URL
      - $PR_ACTION
      - "${ASK_PROMPT}"
    env_file:
      - ./secrets.env
      - ./basic-config.env
      - ./temp.env
    volumes:
      - ./tcpdump:/tmp
