services:
  lite-llm:
    image: ghcr.io/berriai/litellm:v1.72.6-stable
    container_name: lite-llm
    command:
      - --config
      - /app/config.yml
      - --detailed_debug
    ports:
      - "4000:4000"
    env_file:
      - ./secrets.env
    volumes:
      - ./cfg/config.yml:/app/config.yml